[package]
name = "pixxa"
version = "0.1.0"
authors = ["Julian Didier (theredfish) <did.julian@gmail.com>"]

[dependencies]
dotenv = "0.10.1"
dotenv_codegen = "0.11.0"
rand = "0.4"
serenity = "0.4"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
